version: "3"

services:
  node:
    build: .
    depends_on:
      - postgres
      - redis
    image: acgomes68/alpine-node:latest
    restart: always
    container_name: node-${APP_NAME}
    command: npm start
    ports:
    - ${APP_PORT}:3000
    volumes:
    - .:/usr/app

  postgres:
    image: postgres:11-alpine
    # restart: always
    container_name: postgres-${POSTGRES_DATABASE}
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWD}
    ports:
    - ${POSTGRES_PORT}:5432
    volumes:
    - ./data/postgres:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    restart: always
    container_name: redis-${REDIS_DATABASE}
    ports:
    - ${REDIS_PORT}:6379
